### ISSUE TITLE
Avast

### ISSUE THREAD

**Issue by lordjbs** [tjhrulz/WebNowPlaying-BrowserExtension#11]
Hello, avast warns me about the Firefox plugin cause its "insecure"

**Comment by tjhrulz** [comment]
It is a false positive, likely origin is because I have to use an unsecured WebSocket connection. It only connects to localhost and contains no private information so it does not matter but that is likely why Avast is mad about it. 

It may also just be mad because you had to change the one firefox setting for the extension to work.
