### ISSUE TITLE
Webplayer request: Updated Plex

### ISSUE THREAD

**Issue by Gamerbiomek2** [tjhrulz/WebNowPlaying-BrowserExtension#22]
Plex updated and it's not Showing text for Artist, Album or Song.

**Comment by Gamerbiomek2** [comment]
suddenly started working again
not sure why it started working again

**Comment by Gamerbiomek2** [comment]
accidentally hit  close issue, LOL
it still isn't showing text for Artist, Album, or Song
I really want this fixed soon

**Comment by Gamerbiomek2** [comment]
only shows song time durration with rainmeter

**Comment by tjhrulz** [comment]
Honestly as much as I love plex their website literally has been built to make this as difficult and obfuscated as possible (I almost didn't add support initially due to the complexity). I will give updating it again a shot but especially with them likely beefing up security to integrate other content providers and pushing their paid API I may just ax support of it altogether.

**Comment by keifufu** [comment]
Plex works on the new extension ([link](https://github.com/keifufu/WebNowPlaying-Redux)). It's a separate listing on the webstores for now but should eventually replace the existing one.
