### ISSUE TITLE
Webplayer request: Jellyfin/Emby

### ISSUE THREAD

**Issue by AnEnglishSkull** [tjhrulz/WebNowPlaying-BrowserExtension#73]
Jellyfin is a free opensource alternative to plex built on a fork of Emby before they went close source.
Support for one would likely mean support for the other

**Comment by tjhrulz** [comment]
Likely it would not add support for plex since they completely overhauled the backend of their website at the same time. So short of adding support at an API level (Which many of those features are paid on Plex IIRC) it would not be two birds one stone, and adding API support would really be outside the scope of the browser extension.

Regardless if someone wants to add support I am open to adding it to the extension

**Comment by AnEnglishSkull** [comment]
it would likely add support for Jellyfin and Emby not plex sorry I was not clear

**Comment by keifufu** [comment]
I'm not sure if Jellyfin even still worked with this extension, but if there is still demand for Emby/Jellyfin, please open a new Issue over [here](https://github.com/keifufu/WebNowPlaying-Redux), future development of this extension will continue there.
