### ISSUE TITLE
Not following whitelist

### ISSUE THREAD

**Issue by zachthedev** [tjhrulz/WebNowPlaying-BrowserExtension#97]
My whitelist looks like the following:

![image](https://user-images.githubusercontent.com/7672085/194460156-30bf3d76-954e-4bb4-b112-7792733fd928.png)

While on youtube, webnowplaying is picking up that youtube is playing and my rainmeter visualizer starts going off. The visualizer is only programmed to work when webnowplaying is sending data.

Thanks @tjhrulz ! :)

**Comment by xXNickznXx** [comment]
This won't work, both sites have built-in support. And for that reason they are ignored for the generic scripts.
Here you can see which sites are ignored: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/blob/master/manifest.json#L218-L234

And if you want the generic script to be activated, you must also check the first checkbox.

Just for the record, if those sites aren't sending any information, maybe they've both updated their sites and that's why the built-in logic isn't working anymore.

**Comment by keifufu** [comment]
What nick said is true, the generic script should never run on a "officially" supported website.
Future development of the browser extension will continue [here](https://github.com/keifufu/WebNowPlaying-Redux). It is a separate listing on the chrome webstore / mozilla addon store for now but it should replace the original soon enough.

**Comment by zachthedev** [comment]
> What nick said is true, the generic script should never run on a "officially" supported website.
> Future development of the browser extension will continue [here](https://github.com/keifufu/WebNowPlaying-Redux). It is a separate listing on the chrome webstore / mozilla addon store for now but it should replace the original soon enough.

Does this mean that there will be a feature in the new one allowing the disablement of sites?
I was able to ignore the stream but I had to get janky with my rainmeter code.

**Comment by keifufu** [comment]
I don't see why anyone would want to disable certain sites but if it's something you want please open an issue on the new repo
